version: '3'
services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: bangtender-web
    restart: always
    ports:
      - "18080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/keys:/keys
      - ./static:/bangtender/static
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bangtender-server
    restart: always
    command: bash -c 'pip install  -r requirements.txt &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn bangtender.wsgi:application --bind 0.0.0.0:8080'
    expose:
      - '8080'
    volumes:
      - .:/bangtender
      - ./static:/bangtender/static
      - ./logs:/bangtender/logs