version: '3'
services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: bangtender-web
    restart: always
    ports:
      - "18080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/keys:/keys
      - ./static:/bangtender/static
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bangtender-server
    restart: always
    command: bash -c 'pip install  -r requirements.txt && python manage.py makemigrations && python manage.py migrate && gunicorn bangtender.wsgi:application --bind 0.0.0.0:8080'
    expose:
      - '8080'
    env_file:
      - .env # 환경 변수 로드
    volumes:
      - .:/bangtender
      - ./static:/bangtender/static
      - ./logs:/bangtender/logs
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: bangtender-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB} # .env에서 로드
      POSTGRES_USER: ${POSTGRES_USER} # .env에서 로드
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # .env에서 로드
    volumes:
      - postgres_data:/var/lib/postgresql/data # DB 데이터 유지

volumes:
  postgres_data: # PostgreSQL 볼륨 설정
